config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts 
  get 'quem_somos/who'
  get 'entrada/homepage'
  get 'posts/view'
  root 'entrada#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
		belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entrada_controller.rb
class EntradaController < ApplicationController
  def homepage
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	public 
	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
	end
	
	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end


	private
	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end

end

app/controllers/quem_somos_controller.rb
class QuemSomosController < ApplicationController
  def who
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrada_helper.rb
module EntradaHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/quem_somos_helper.rb
module QuemSomosHelper
end

app/views/entrada/homepage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Não Jubila!</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/heroic-features.css" rel="stylesheet">

</head>

<body>

    <center><%= image_tag("logo/5.png")%></center>

  <div class="row">

    <!-- Page Content -->
    <div class="container">
     

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">

           <center> <h1> Projeto Não Jubila! </h1> </center>
            <p align="justify"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; O site Não Jubila! tem o intuito de ajudar outras pessoas que estão precisando daquele material que você já conseguiu, ajude e seja ajudado. Acreditamos que compartilhando conhecimento, contribuimos para a educação e crescimento de novos profissionais. Assim, pessoas que não tem acesso a acervos e grandes bibliotecas podem de maneira fácil e rápida ter todo o conteúdo necessário para seu crescimento acadêmico e profissional. </p>

            <p align="justify"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ajude um desesperado, você poderá estar como ele daqui há alguns semestres!</p>
        </header>

        </div>


        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                  <center>  <p>Copyright &copy; Não Jubila! 2016</p> </center>
                </div>
            </div>
        </footer>

    </div>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nao Jubila!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
	 <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>


    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/entrada/homepage">Não Jubila!</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/quem_somos/who">Quem somos?</a>
                    </li>

                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>                  
                    <%if user_signed_in?%>
                    <li>
                        <a href="/posts/new">Postar</a>
                    </li>
                    <%end%>
                    <li>
                        </center><a href="/posts">Jubilando</a>
                    </li>


                    <ul class="nav navbar-nav navbar-right">
                    <%if user_signed_in?%>
                    <li><a></a></li> 
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>  
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>

                    <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
                    <%else%>
                    <li><a></a></li>
                    <li><a></a></li> 
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a></a></li>
                    <li><a href="/users/sign_in">Entrar</a></li>
                        <li><a href="/users/sign_up">Cadastrar</a></li>
                    <%end%>    
                    </ul>
                </ul>
            </div>
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
	<% f.error_notification %>

	<div class="form-inputs">

		<%= f.input :title %>
		<p> </p>
			<%= f.input :content%>
	</div>

	<div class="form-actions">
		<hr>
		<%= f.button :submit, class: "btn btn-primary" %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">

        <h2>Editar Postagem</h2>
        <hr>
    <!-- Jumbotron Header -->
    <header class="jumbotron">
		 <%= render 'form' %>
		 <p></p>
		 <%= link_to "Cancelar", post_path, class: "btn btn-primary" %>
    </header>


    <footer>
        <div class="row">
            <div class="col-lg-12">
                <hr>
                <p>Copyright &copy; Não Jubila! 2016</p>
            </div>
        </div>
    </footer>
</div>


<%= render 'form' %>

%h1 Edit Post

= render 'form'

= link_to "Cancelar", post_path

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


    <div class="container">

            <h2>Postagens</h2>
            <hr>
        <!-- Jumbotron Header -->
        <header class="jumbotron">
            <% @posts.each do |post| %>
                <h2><%= link_to post.title, post %></h2>
                <h6>
                    Published at
                    <%= time_ago_in_words(post.created_at) %>
                    by
                    <%= post.user.email %>
                </h6>
                <hr>
            <% end %>
        </header>


        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <hr>
                    <p>Copyright &copy; Não Jubila! 2016</p>
                </div>
            </div>
        </footer>
    </div>

app/views/posts/new.html.erb
<div class="container">

        <h2>Nova Postagem</h2>
        <hr>
    <!-- Jumbotron Header -->
    <header class="jumbotron">
		 <%= render 'form' %>
    </header>


    <footer>
        <div class="row">
            <div class="col-lg-12">
                <hr>
                <p>Copyright &copy; Não Jubila! 2016</p>
            </div>
        </div>
    </footer>
</div>

app/views/posts/show.html.erb
<div class="container">
        
	<h1><%= @post.title %></h1>
    <hr>
    <header class="jumbotron">

		<p><%= @post.content %></p>
		<hr>

        <%if user_signed_in? && (current_user.id == @post.user_id)%>
			<%= link_to "Editar", edit_post_path(@post), class: "btn btn-primary" %>
			<%= link_to "Deletar", post_path(@post), class: "btn btn-primary", method: :delete, data: {confirm: "Tem certeza que vai deixar um amigo ser jubilado?"} %>
			<%= link_to "Voltar", posts_path, class: "btn btn-primary" %>
		<% else %>
			<%= link_to "Voltar", posts_path, class: "btn btn-primary" %>
		<% end %>
    </header>


        <footer>
            <div class="row">
                <div class="col-lg-12">
                <hr>
                    <p>Copyright &copy; Não Jubila! 2016</p>
                </div>
            </div>
        </footer>


</div>

app/views/quem_somos/who.html.erb
<!DOCTYPE html>
<html>
   <head>
              <title>Inserindo e manipulando imagens em uma página HTML</title>
   </head>
   <body>
		<center><%=image_tag("teste/anaa.jpeg")%></center>
		<li><a></a></li>
		<li><a></a></li>
		<div class="container">
	    	<hr>
	    	<header class="jumbotron">
				<center><h3>Ana Carolina de Carvalho </h3></center>
				<center><h4>Estudante de Engenharia de Software da Universidade de Brasília</h4></center>
			</header>

		</div>

		<li><a></a></li>
		<li><a></a></li>

		<center><%= image_tag("teste/eue.jpeg")%></center>
			<li><a></a></li>
			<li><a></a></li>

		<div class="container">
			<hr>
		    <header class="jumbotron">
		    	<center><h3>Guilherme Guimarães Lacerda</h3></center>
				<center><h4>Estudante de Engenharia de Software da Universidade de Brasília</h4></center>
		    </header>
		</div>
		
		<li><a></a></li>
		<li><a></a></li>
		
		<footer>
    		<div class="row">
    			<div class="col-lg-12">
        			<hr>
            		<center><p>Copyright &copy; Não Jubila! 2016</p></center>
      		  	</div>
   			 </div>
		</footer>
   </body>

</html>